CREATE TABLE "identity" (
    "id" UUID NOT NULL,
    "name" TEXT,
    "meta" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE TABLE "scratchpad" (
    "chat_id" BIGINT NOT NULL,
    "content" TEXT NOT NULL,
    "token_count" INTEGER NOT NULL,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    PRIMARY KEY ("chat_id")
);
CREATE TABLE "chat" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "platform" TEXT NOT NULL,
    "external_id" TEXT NOT NULL,
    "chat_type" TEXT NOT NULL,
    "name" TEXT,
    "config" TEXT,
    "meta" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE TABLE "perception" (
    "id" UUID NOT NULL,
    "source" TEXT NOT NULL,
    "parser" TEXT NOT NULL,
    "prompt" TEXT,
    "content" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE TABLE "message" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "chat_id" BIGINT NOT NULL,
    "account_id" BIGINT,
    "role" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "topic_id" UUID,
    "interaction_status" TEXT NOT NULL,
    "reply_to_id" BIGINT,
    "external_id" TEXT,
    "meta" TEXT,
    "token_count" INTEGER,
    "sent_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE TABLE "account" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "identity_id" UUID,
    "platform" TEXT NOT NULL,
    "external_id" TEXT NOT NULL,
    "meta" TEXT,
    "last_active_at" TIMESTAMPTZ(6) NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX "index_account_by_identity_id" ON "account" ("identity_id");
CREATE TABLE "memory" (
    "id" UUID NOT NULL,
    "account_id" BIGINT,
    "chat_id" BIGINT,
    "type" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "importance" INTEGER NOT NULL,
    "subject" TEXT,
    "references" TEXT,
    "meta" TEXT,
    "last_accessed_at" TIMESTAMPTZ(6) NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE TABLE "topic" (
    "id" UUID NOT NULL,
    "chat_id" BIGINT NOT NULL,
    "title" TEXT,
    "summary" TEXT,
    "status" TEXT NOT NULL,
    "parent_topic_id" UUID,
    "token_count" INTEGER NOT NULL,
    "message_count" INTEGER NOT NULL,
    "meta" TEXT,
    "started_at" TIMESTAMPTZ(6) NOT NULL,
    "last_active_at" TIMESTAMPTZ(6) NOT NULL,
    "closed_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,
    PRIMARY KEY ("id")
);
