CREATE TABLE "event" (
    "seq" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "domain" TEXT NOT NULL,
    "kind" TEXT NOT NULL,
    "chat_id" BIGINT,
    "payload" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL,
    PRIMARY KEY ("seq")
);
CREATE INDEX "index_event_by_chat_id" ON "event" ("chat_id");
CREATE INDEX "index_event_by_created_at" ON "event" ("created_at");
