[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
config = { version = "0.15", features = ["json", "toml"] }
dotenvy = "0.15"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_with = "3"
autoagents = { version = "0.3", features = [
    "openrouter",
    "openai",
    "anthropic",
    "google",
    "deepseek",
    "groq",
    "ollama",
    "xai",
] }
autoagents-derive = "0.3"
autoagents-toolkit = { version = "0.3", features = ["mcp"] }
agent-skills = "0.2"
teloxide = { version = "0.17", features = ["macros"] }
tracing = "0.1"
tracing-serde = "0.2"
tracing-subscriber = "0.3"
async-trait = "0.1"
base64 = "0.22"
reqwest = "0.13"
mime = "0.3"
arc-swap = "1.7"
derive_more = { version = "2", features = ["full"] }
tap = "1"
jiff = { version = "0.2", features = ["serde"] }
sqlx = { version = "0.8", features = [
    "runtime-tokio",
    "postgres",
    "uuid",
    "json",
] }
jiff-sqlx = { version = "0.1", features = ["postgres"] }
pgvector = { version = "0.4", features = ["sqlx"] }
uuid = { version = "1", features = ["v4", "v5", "v7", "serde"] }
strum = { version = "0.28", features = ["derive"] }
struct-patch = "0.12"
tiktoken-rs = "0.11"
toml = "1.0.4"
clap = { version = "4.5", features = ["derive"] }
thiserror = "2.0.18"
rand = { version = "0.10" }
indexmap = { version = "2", features = ["serde"] }
futures = "0.3"
dirs = "6.0.0"
hound = "3.5"
linkify = "0.11"
timeago = "0.6"
sanitize-filename = "0.6"
quick-xml = "0.40"

[profile.release]
panic = "abort"
lto = true
opt-level = 3
codegen-units = 1
strip = true
