version = 1

[[migrations]]
id = 8972359203239455522
name = "0000_initial.sql"
snapshot_name = "0000_snapshot.toml"

[[migrations]]
id = 8474721751202300228
name = "0001_memory_schema_cleanup.sql"
snapshot_name = "0001_snapshot.toml"

[[migrations]]
id = 2239221563053133369
name = "0002_event.sql"
snapshot_name = "0002_snapshot.toml"

[[migrations]]
id = 3021826919047328601
name = "0003_event_drop_kind_chat_id.sql"
snapshot_name = "0003_snapshot.toml"

[[migrations]]
id = 4257943499722039984
name = "0004_conversation.sql"
snapshot_name = "0004_snapshot.toml"

[[migrations]]
id = 1804566921660974244
name = "0005_conv2.sql"
snapshot_name = "0005_snapshot.toml"
