version = 1

[schema]

[[schema.tables]]
id = 0
name = "account"
primary_key = { columns = [{ table = 0, index = 0 }], index = { table = 0, index = 0 } }

[[schema.tables.columns]]
id = { table = 0, index = 0 }
name = "id"
ty = "I64"
storage_ty = { Integer = 8 }
auto_increment = true

[[schema.tables.columns]]
id = { table = 0, index = 1 }
name = "identity_id"
ty = "Uuid"
storage_ty = "Uuid"
nullable = true

[[schema.tables.columns]]
id = { table = 0, index = 2 }
name = "platform"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 0, index = 3 }
name = "external_id"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 0, index = 4 }
name = "meta"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 0, index = 5 }
name = "last_active_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.columns]]
id = { table = 0, index = 6 }
name = "created_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.columns]]
id = { table = 0, index = 7 }
name = "updated_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.indices]]
id = { table = 0, index = 0 }
name = "index_account_by_id"
on = 0
columns = [{ column = { table = 0, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 0, index = 1 }
name = "index_account_by_identity_id"
on = 0
columns = [{ column = { table = 0, index = 1 }, op = "Eq", scope = "Partition" }]

[[schema.tables]]
id = 1
name = "chat"
primary_key = { columns = [{ table = 1, index = 0 }], index = { table = 1, index = 0 } }

[[schema.tables.columns]]
id = { table = 1, index = 0 }
name = "id"
ty = "I64"
storage_ty = { Integer = 8 }
auto_increment = true

[[schema.tables.columns]]
id = { table = 1, index = 1 }
name = "platform"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 1, index = 2 }
name = "external_id"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 1, index = 3 }
name = "chat_type"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 1, index = 4 }
name = "name"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 1, index = 5 }
name = "config"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 1, index = 6 }
name = "meta"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 1, index = 7 }
name = "created_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.columns]]
id = { table = 1, index = 8 }
name = "updated_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.indices]]
id = { table = 1, index = 0 }
name = "index_chat_by_id"
on = 1
columns = [{ column = { table = 1, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables]]
id = 2
name = "identity"
primary_key = { columns = [{ table = 2, index = 0 }], index = { table = 2, index = 0 } }

[[schema.tables.columns]]
id = { table = 2, index = 0 }
name = "id"
ty = "Uuid"
storage_ty = "Uuid"

[[schema.tables.columns]]
id = { table = 2, index = 1 }
name = "name"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 2, index = 2 }
name = "meta"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 2, index = 3 }
name = "created_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.columns]]
id = { table = 2, index = 4 }
name = "updated_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.indices]]
id = { table = 2, index = 0 }
name = "index_identity_by_id"
on = 2
columns = [{ column = { table = 2, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables]]
id = 3
name = "memory"
primary_key = { columns = [{ table = 3, index = 0 }], index = { table = 3, index = 0 } }

[[schema.tables.columns]]
id = { table = 3, index = 0 }
name = "id"
ty = "Uuid"
storage_ty = "Uuid"

[[schema.tables.columns]]
id = { table = 3, index = 1 }
name = "account_id"
ty = "I64"
storage_ty = { Integer = 8 }
nullable = true

[[schema.tables.columns]]
id = { table = 3, index = 2 }
name = "chat_id"
ty = "I64"
storage_ty = { Integer = 8 }
nullable = true

[[schema.tables.columns]]
id = { table = 3, index = 3 }
name = "type"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 3, index = 4 }
name = "content"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 3, index = 5 }
name = "embedding"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 3, index = 6 }
name = "importance"
ty = "I32"
storage_ty = { Integer = 4 }

[[schema.tables.columns]]
id = { table = 3, index = 7 }
name = "subject"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 3, index = 8 }
name = "references"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 3, index = 9 }
name = "meta"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 3, index = 10 }
name = "last_accessed_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.columns]]
id = { table = 3, index = 11 }
name = "created_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.columns]]
id = { table = 3, index = 12 }
name = "updated_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.indices]]
id = { table = 3, index = 0 }
name = "index_memory_by_id"
on = 3
columns = [{ column = { table = 3, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables]]
id = 4
name = "message"
primary_key = { columns = [{ table = 4, index = 0 }], index = { table = 4, index = 0 } }

[[schema.tables.columns]]
id = { table = 4, index = 0 }
name = "id"
ty = "I64"
storage_ty = { Integer = 8 }
auto_increment = true

[[schema.tables.columns]]
id = { table = 4, index = 1 }
name = "chat_id"
ty = "I64"
storage_ty = { Integer = 8 }

[[schema.tables.columns]]
id = { table = 4, index = 2 }
name = "account_id"
ty = "I64"
storage_ty = { Integer = 8 }
nullable = true

[[schema.tables.columns]]
id = { table = 4, index = 3 }
name = "role"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 4, index = 4 }
name = "content"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 4, index = 5 }
name = "topic_id"
ty = "Uuid"
storage_ty = "Uuid"
nullable = true

[[schema.tables.columns]]
id = { table = 4, index = 6 }
name = "interaction_status"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 4, index = 7 }
name = "reply_to_id"
ty = "I64"
storage_ty = { Integer = 8 }
nullable = true

[[schema.tables.columns]]
id = { table = 4, index = 8 }
name = "external_id"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 4, index = 9 }
name = "meta"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 4, index = 10 }
name = "token_count"
ty = "I32"
storage_ty = { Integer = 4 }
nullable = true

[[schema.tables.columns]]
id = { table = 4, index = 11 }
name = "sent_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }
nullable = true

[[schema.tables.columns]]
id = { table = 4, index = 12 }
name = "created_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.columns]]
id = { table = 4, index = 13 }
name = "updated_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.indices]]
id = { table = 4, index = 0 }
name = "index_message_by_id"
on = 4
columns = [{ column = { table = 4, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables]]
id = 5
name = "perception"
primary_key = { columns = [{ table = 5, index = 0 }], index = { table = 5, index = 0 } }

[[schema.tables.columns]]
id = { table = 5, index = 0 }
name = "id"
ty = "Uuid"
storage_ty = "Uuid"

[[schema.tables.columns]]
id = { table = 5, index = 1 }
name = "source"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 5, index = 2 }
name = "parser"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 5, index = 3 }
name = "prompt"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 5, index = 4 }
name = "content"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 5, index = 5 }
name = "embedding"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 5, index = 6 }
name = "created_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.indices]]
id = { table = 5, index = 0 }
name = "index_perception_by_id"
on = 5
columns = [{ column = { table = 5, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables]]
id = 6
name = "scratchpad"
primary_key = { columns = [{ table = 6, index = 0 }], index = { table = 6, index = 0 } }

[[schema.tables.columns]]
id = { table = 6, index = 0 }
name = "chat_id"
ty = "I64"
storage_ty = { Integer = 8 }

[[schema.tables.columns]]
id = { table = 6, index = 1 }
name = "content"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 6, index = 2 }
name = "token_count"
ty = "I32"
storage_ty = { Integer = 4 }

[[schema.tables.columns]]
id = { table = 6, index = 3 }
name = "updated_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.indices]]
id = { table = 6, index = 0 }
name = "index_scratchpad_by_chat_id"
on = 6
columns = [{ column = { table = 6, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables]]
id = 7
name = "topic"
primary_key = { columns = [{ table = 7, index = 0 }], index = { table = 7, index = 0 } }

[[schema.tables.columns]]
id = { table = 7, index = 0 }
name = "id"
ty = "Uuid"
storage_ty = "Uuid"

[[schema.tables.columns]]
id = { table = 7, index = 1 }
name = "chat_id"
ty = "I64"
storage_ty = { Integer = 8 }

[[schema.tables.columns]]
id = { table = 7, index = 2 }
name = "title"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 7, index = 3 }
name = "summary"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 7, index = 4 }
name = "embedding"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 7, index = 5 }
name = "status"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 7, index = 6 }
name = "parent_topic_id"
ty = "Uuid"
storage_ty = "Uuid"
nullable = true

[[schema.tables.columns]]
id = { table = 7, index = 7 }
name = "token_count"
ty = "I32"
storage_ty = { Integer = 4 }

[[schema.tables.columns]]
id = { table = 7, index = 8 }
name = "message_count"
ty = "I32"
storage_ty = { Integer = 4 }

[[schema.tables.columns]]
id = { table = 7, index = 9 }
name = "meta"
ty = "String"
storage_ty = "Text"
nullable = true

[[schema.tables.columns]]
id = { table = 7, index = 10 }
name = "started_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.columns]]
id = { table = 7, index = 11 }
name = "last_active_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.columns]]
id = { table = 7, index = 12 }
name = "closed_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }
nullable = true

[[schema.tables.columns]]
id = { table = 7, index = 13 }
name = "created_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.columns]]
id = { table = 7, index = 14 }
name = "updated_at"
ty = "Timestamp"
storage_ty = { Timestamp = 6 }

[[schema.tables.indices]]
id = { table = 7, index = 0 }
name = "index_topic_by_id"
on = 7
columns = [{ column = { table = 7, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true
